sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ******
    username: root
    password: ****
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: *******************
    access-key-secret: ********************
    bucket-name: ***********
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: **********************
    secret: ***************************
