sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6Ug244SgiDgqgGfaFj
    access-key-secret: txUx7iHN95stA9x8MtHCOW6XeATLIA
    bucket-name: web-gh05
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx2e0eb68b9d1560cb
    secret: ad2729e6fa52d20b13fd345ba028354d
